image: mcr.microsoft.com/dotnet/sdk:7.0 # use the .NET SDK image for the pipeline

stages:
  - build
  - deploy

variables: # environment variables, similar to GitHub Actions' env
  PUBLISH_DIR: vystup

build:
  stage: build
  script:
    - dotnet build Ppt23.Client/Ppt23.Client.sln --configuration Release # build the app
    - dotnet publish Ppt23.Client/Ppt23.Client.sln --configuration Release --output $PUBLISH_DIR # publish the app to PUBLISH_DIR

deploy:
  stage: deploy
  script:
    - sed -i 's/<base href="\/" \/>/<base href="\/ppt23_rajnikat\/" \/>/g' $PUBLISH_DIR/wwwroot/index.html # change the base tag in index.html
    - touch $PUBLISH_DIR/wwwroot/.nojekyll # add .nojekyll file
    - echo "Deploying to GitLab Pages"
  artifacts: # publish the contents of PUBLISH_DIR to GitLab Pages
    paths:
      - $PUBLISH_DIR/wwwroot/
  only:
    - master # deploy only on the master branch
